### ISSUE TITLE
task11-about-us-margin-text

### ISSUE THREAD

**Issue by savchenkolex** [savchenkolex/powerkit-ua-site#93]
https://take.ms/ncfHf -  на малих екранах в блоці «про нас» треба додати відступ між текстом і фото (mobile) приклад девайсу - iphone mini 12 os 14

**Comment by savchenkolex** [comment]
Схоже, що в даному випадку браузер не підтримує властивість gap і скоріше за все на цьому пристрої браузер не оновлювався з 2017 року - https://caniuse.com/?search=gap

спробую вирішити за допомогою запиту:
`@supports (gap: 10px) with (display: flex) {`

**Comment by savchenkolex** [comment]
Уточнення. Flexbox gap підтримується на safari ios з оновленнями від квітня 2021
https://caniuse.com/flexbox-gap

**Comment by savchenkolex** [comment]
зрештою спрацювало наступне: 
```css

.about-text {
  margin-bottom: 24px;
}

@supports (display: flex) and (gap: 24px) {

.about-wrapper {
  display: flex;
  flex-wrap: wrap;
  gap: 24px;
}

.about-text {
  margin-bottom: 0;
}

}
```
потрібна повторна перевірка на живому девайсі.
